version: '2'

networks:
    default:
        driver: bridge

services:
    rest1:
        build:
            context: .
            dockerfile: Dockerfile1
        container_name: rest1
        ports:
          - "35001:6001"
        networks:
          - default
    rest2:
            build:
                context: .
                dockerfile: Dockerfile1
            container_name: rest2
            ports:
            - "35002:6001"
            networks:
            - default

    rest3:
            build:
                context: .
                dockerfile: Dockerfile1
            container_name: rest3
            ports:
            - "35003:6001"
            networks:
            - default
    
    facade:
            build:
                context: .
                dockerfile: Dockerfile
            container_name:  facade
            ports:
            - "8087:6000"
            networks:
            - default

    db:
        image: mongo:3.6.1
        container_name: db
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb
        ports:
            - 27017:27017
        command: mongod
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: pass
            MONGO_INITDB_DATABASE: logs
        
volumes:
    mongodb:
    mongodb_config: